# Generated by Django 4.2.7 on 2023-11-09 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0005_task_completed_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_long_tasks_refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_medium_tasks_refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_short_tasks_refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
