# Generated by Django 4.2.7 on 2023-11-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0007_customuser_categorized_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='categorized_tasks',
        ),
        migrations.AddField(
            model_name='customuser',
            name='long_tasks',
            field=models.ManyToManyField(blank=True, related_name='long_tasks', to='uw_app.task'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medium_tasks',
            field=models.ManyToManyField(blank=True, related_name='medium_tasks', to='uw_app.task'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_tasks',
            field=models.ManyToManyField(blank=True, related_name='short_tasks', to='uw_app.task'),
        ),
    ]
