# Generated by Django 4.2.7 on 2023-11-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0008_remove_customuser_categorized_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='long_tasks',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='medium_tasks',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='short_tasks',
        ),
        migrations.AddField(
            model_name='customuser',
            name='long_tasks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medium_tasks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_tasks',
            field=models.JSONField(default=list),
        ),
    ]
