# Generated by Django 4.2.7 on 2023-11-21 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0009_remove_customuser_long_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='short_tasks',
            new_name='daily_tasks',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_short_tasks_refreshed',
            new_name='last_daily_tasks_refreshed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_long_tasks_refreshed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_medium_tasks_refreshed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='long_tasks',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='medium_tasks',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_monthly_tasks_refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_weekly_tasks_refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_tasks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_tasks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(default='Daily', max_length=50),
        ),
    ]
