# Generated by Django 4.2.7 on 2023-11-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0010_rename_short_tasks_customuser_daily_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(default='daily', max_length=50),
        ),
    ]
