# Generated by Django 4.2.7 on 2023-11-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0011_alter_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='daily_tasks',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='monthly_tasks',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='weekly_tasks',
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_tasks',
            field=models.ManyToManyField(blank=True, related_name='daily_tasks', to='uw_app.task'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_tasks',
            field=models.ManyToManyField(blank=True, related_name='monthly_tasks', to='uw_app.task'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_tasks',
            field=models.ManyToManyField(blank=True, related_name='weekly_tasks', to='uw_app.task'),
        ),
    ]
