# Generated by Django 4.2.7 on 2023-11-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0012_remove_customuser_daily_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='character_image',
            field=models.CharField(default='../images/jainar.jpg', max_length=255),
        ),
    ]
