# Generated by Django 4.2.7 on 2023-11-22 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0017_remove_task_due_date_customuser_daily_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='daily_due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='monthly_due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weekly_due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
