# Generated by Django 4.2.7 on 2023-11-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0018_alter_customuser_daily_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subcategory',
        ),
        migrations.CreateModel(
            name='Subsubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uw_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='subsubcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uw_app.subsubcategory'),
        ),
    ]
