# Generated by Django 4.2.7 on 2023-12-01 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uw_app', '0019_remove_task_subcategory_subsubcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uw_app.subcategory'),
        ),
    ]
